import type { Metadata } from "next" 
import { Inter } from "next/font/google"
import "./globals.css"
import { Providers } from "@/providers"
import 'react-toastify/dist/ReactToastify.css'
import { ToastContainer } from "react-toastify"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <ToastContainer
                  position="top-right"
                  autoClose={5000}
                  hideProgressBar={false}
                  newestOnTop={false}
                  closeOnClick
                  rtl={false}
                  pauseOnFocusLoss
                  draggable
                  pauseOnHover
                  theme="light"
              />
          {children}
        </body>
      </Providers>
    </html>
  );
}
